version: "3.8"

services:
  app:
    container_name: react_typescript_boilerplate__development
    image: react_typescript_boilerplate__development
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000